name: PR Merged to Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  echo_hi:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - name: Echo Hi pr closed but ran
        run: echo "Hi from merged PR to master!"
